// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	ComplexPoint
	BlockRequest
	BlockReply
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ComplexPoint struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *ComplexPoint) Reset()                    { *m = ComplexPoint{} }
func (m *ComplexPoint) String() string            { return proto.CompactTextString(m) }
func (*ComplexPoint) ProtoMessage()               {}
func (*ComplexPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ComplexPoint) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ComplexPoint) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type BlockRequest struct {
	PStart    *ComplexPoint `protobuf:"bytes,1,opt,name=pStart" json:"pStart,omitempty"`
	PEnd      *ComplexPoint `protobuf:"bytes,2,opt,name=pEnd" json:"pEnd,omitempty"`
	Points    int32         `protobuf:"varint,3,opt,name=points" json:"points,omitempty"`
	MaxIters  int32         `protobuf:"varint,4,opt,name=maxIters" json:"maxIters,omitempty"`
	BlockSize int32         `protobuf:"varint,5,opt,name=blockSize" json:"blockSize,omitempty"`
	XBlock    int32         `protobuf:"varint,6,opt,name=xBlock" json:"xBlock,omitempty"`
	YBlock    int32         `protobuf:"varint,7,opt,name=yBlock" json:"yBlock,omitempty"`
}

func (m *BlockRequest) Reset()                    { *m = BlockRequest{} }
func (m *BlockRequest) String() string            { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()               {}
func (*BlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockRequest) GetPStart() *ComplexPoint {
	if m != nil {
		return m.PStart
	}
	return nil
}

func (m *BlockRequest) GetPEnd() *ComplexPoint {
	if m != nil {
		return m.PEnd
	}
	return nil
}

func (m *BlockRequest) GetPoints() int32 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *BlockRequest) GetMaxIters() int32 {
	if m != nil {
		return m.MaxIters
	}
	return 0
}

func (m *BlockRequest) GetBlockSize() int32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *BlockRequest) GetXBlock() int32 {
	if m != nil {
		return m.XBlock
	}
	return 0
}

func (m *BlockRequest) GetYBlock() int32 {
	if m != nil {
		return m.YBlock
	}
	return 0
}

type BlockReply struct {
	Results []int32 `protobuf:"varint,10,rep,packed,name=results" json:"results,omitempty"`
}

func (m *BlockReply) Reset()                    { *m = BlockReply{} }
func (m *BlockReply) String() string            { return proto.CompactTextString(m) }
func (*BlockReply) ProtoMessage()               {}
func (*BlockReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BlockReply) GetResults() []int32 {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*ComplexPoint)(nil), "rpc.ComplexPoint")
	proto.RegisterType((*BlockRequest)(nil), "rpc.BlockRequest")
	proto.RegisterType((*BlockReply)(nil), "rpc.BlockReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MandelService service

type MandelServiceClient interface {
	ComputeMandel(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error)
}

type mandelServiceClient struct {
	cc *grpc.ClientConn
}

func NewMandelServiceClient(cc *grpc.ClientConn) MandelServiceClient {
	return &mandelServiceClient{cc}
}

func (c *mandelServiceClient) ComputeMandel(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error) {
	out := new(BlockReply)
	err := grpc.Invoke(ctx, "/rpc.MandelService/ComputeMandel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MandelService service

type MandelServiceServer interface {
	ComputeMandel(context.Context, *BlockRequest) (*BlockReply, error)
}

func RegisterMandelServiceServer(s *grpc.Server, srv MandelServiceServer) {
	s.RegisterService(&_MandelService_serviceDesc, srv)
}

func _MandelService_ComputeMandel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MandelServiceServer).ComputeMandel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MandelService/ComputeMandel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MandelServiceServer).ComputeMandel(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MandelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.MandelService",
	HandlerType: (*MandelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeMandel",
			Handler:    _MandelService_ComputeMandel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x5d, 0x29, 0xd4, 0x8e, 0x34, 0xc6, 0x39, 0x98, 0x4d, 0xe3, 0x81, 0x90, 0x68, 0xd0,
	0x43, 0x0f, 0x35, 0xbe, 0x80, 0x46, 0x13, 0x0f, 0x26, 0x06, 0x9e, 0x80, 0xd2, 0x39, 0x10, 0xb7,
	0xb0, 0x2e, 0x8b, 0x61, 0x7d, 0x5c, 0x9f, 0xc4, 0xec, 0x2e, 0x2a, 0x87, 0x1e, 0xbf, 0x6f, 0x86,
	0x3f, 0xf3, 0xb3, 0xb0, 0x50, 0xb2, 0x5a, 0x4b, 0xd5, 0xea, 0x16, 0x03, 0x25, 0xab, 0xf4, 0x16,
	0xe2, 0xc7, 0x76, 0x2f, 0x05, 0x0d, 0x6f, 0x6d, 0xdd, 0x68, 0x8c, 0x81, 0x0d, 0x9c, 0x25, 0x2c,
	0x63, 0x39, 0x1b, 0x2c, 0x19, 0x7e, 0xec, 0xc9, 0xa4, 0xdf, 0x0c, 0xe2, 0x07, 0xd1, 0x56, 0xef,
	0x39, 0x7d, 0xf4, 0xd4, 0x69, 0xbc, 0x81, 0x48, 0x16, 0xba, 0x54, 0xda, 0x7d, 0x71, 0xba, 0x39,
	0x5f, 0xdb, 0xf4, 0x69, 0x5e, 0x3e, 0x2e, 0xe0, 0x15, 0xcc, 0xe4, 0x53, 0xb3, 0x73, 0x61, 0x07,
	0x17, 0xdd, 0x18, 0x2f, 0x20, 0x92, 0x16, 0x3b, 0x1e, 0x24, 0x2c, 0x0b, 0xf3, 0x91, 0x70, 0x05,
	0x27, 0xfb, 0x72, 0x78, 0xd1, 0xa4, 0x3a, 0x3e, 0x73, 0x93, 0x3f, 0xc6, 0x4b, 0x58, 0x6c, 0xed,
	0x55, 0x45, 0xfd, 0x45, 0x3c, 0x74, 0xc3, 0x7f, 0x61, 0x13, 0x07, 0x77, 0x34, 0x8f, 0x7c, 0xa2,
	0x27, 0xeb, 0x8d, 0xf7, 0x73, 0xef, 0x3d, 0xa5, 0xd7, 0x00, 0x63, 0x47, 0x29, 0x0c, 0x72, 0x98,
	0x2b, 0xea, 0x7a, 0xa1, 0x3b, 0x0e, 0x49, 0x90, 0x85, 0xf9, 0x2f, 0x6e, 0x9e, 0x61, 0xf9, 0x5a,
	0x36, 0x3b, 0x12, 0x05, 0xa9, 0xcf, 0xba, 0x22, 0xbc, 0x87, 0xa5, 0x2d, 0xd4, 0x6b, 0xf2, 0x1e,
	0x7d, 0xc9, 0xe9, 0x0f, 0x5b, 0x9d, 0x4d, 0x95, 0x14, 0x26, 0x3d, 0xda, 0x46, 0xee, 0x31, 0xee,
	0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x32, 0xd1, 0x7e, 0x1f, 0x99, 0x01, 0x00, 0x00,
}
