// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	ComplexPoint
	BlockRequest
	BlockReply
	HealthCheckRequest
	HealthCheckResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}
var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type ComplexPoint struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *ComplexPoint) Reset()                    { *m = ComplexPoint{} }
func (m *ComplexPoint) String() string            { return proto.CompactTextString(m) }
func (*ComplexPoint) ProtoMessage()               {}
func (*ComplexPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ComplexPoint) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ComplexPoint) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type BlockRequest struct {
	PStart    *ComplexPoint `protobuf:"bytes,1,opt,name=pStart" json:"pStart,omitempty"`
	PEnd      *ComplexPoint `protobuf:"bytes,2,opt,name=pEnd" json:"pEnd,omitempty"`
	Points    int32         `protobuf:"varint,3,opt,name=points" json:"points,omitempty"`
	MaxIters  int32         `protobuf:"varint,4,opt,name=maxIters" json:"maxIters,omitempty"`
	BlockSize int32         `protobuf:"varint,5,opt,name=blockSize" json:"blockSize,omitempty"`
	XBlock    int32         `protobuf:"varint,6,opt,name=xBlock" json:"xBlock,omitempty"`
	YBlock    int32         `protobuf:"varint,7,opt,name=yBlock" json:"yBlock,omitempty"`
}

func (m *BlockRequest) Reset()                    { *m = BlockRequest{} }
func (m *BlockRequest) String() string            { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()               {}
func (*BlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockRequest) GetPStart() *ComplexPoint {
	if m != nil {
		return m.PStart
	}
	return nil
}

func (m *BlockRequest) GetPEnd() *ComplexPoint {
	if m != nil {
		return m.PEnd
	}
	return nil
}

func (m *BlockRequest) GetPoints() int32 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *BlockRequest) GetMaxIters() int32 {
	if m != nil {
		return m.MaxIters
	}
	return 0
}

func (m *BlockRequest) GetBlockSize() int32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *BlockRequest) GetXBlock() int32 {
	if m != nil {
		return m.XBlock
	}
	return 0
}

func (m *BlockRequest) GetYBlock() int32 {
	if m != nil {
		return m.YBlock
	}
	return 0
}

type BlockReply struct {
	Results []int32 `protobuf:"varint,10,rep,packed,name=results" json:"results,omitempty"`
}

func (m *BlockReply) Reset()                    { *m = BlockReply{} }
func (m *BlockReply) String() string            { return proto.CompactTextString(m) }
func (*BlockReply) ProtoMessage()               {}
func (*BlockReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BlockReply) GetResults() []int32 {
	if m != nil {
		return m.Results
	}
	return nil
}

type HealthCheckRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *HealthCheckRequest) Reset()                    { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()               {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,enum=rpc.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterType((*ComplexPoint)(nil), "rpc.ComplexPoint")
	proto.RegisterType((*BlockRequest)(nil), "rpc.BlockRequest")
	proto.RegisterType((*BlockReply)(nil), "rpc.BlockReply")
	proto.RegisterType((*HealthCheckRequest)(nil), "rpc.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "rpc.HealthCheckResponse")
	proto.RegisterEnum("rpc.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MandelService service

type MandelServiceClient interface {
	ComputeMandel(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error)
}

type mandelServiceClient struct {
	cc *grpc.ClientConn
}

func NewMandelServiceClient(cc *grpc.ClientConn) MandelServiceClient {
	return &mandelServiceClient{cc}
}

func (c *mandelServiceClient) ComputeMandel(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockReply, error) {
	out := new(BlockReply)
	err := grpc.Invoke(ctx, "/rpc.MandelService/ComputeMandel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MandelService service

type MandelServiceServer interface {
	ComputeMandel(context.Context, *BlockRequest) (*BlockReply, error)
}

func RegisterMandelServiceServer(s *grpc.Server, srv MandelServiceServer) {
	s.RegisterService(&_MandelService_serviceDesc, srv)
}

func _MandelService_ComputeMandel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MandelServiceServer).ComputeMandel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.MandelService/ComputeMandel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MandelServiceServer).ComputeMandel(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MandelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.MandelService",
	HandlerType: (*MandelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeMandel",
			Handler:    _MandelService_ComputeMandel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// Client API for Health service

type HealthClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/rpc.Health/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Health service

type HealthServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Health/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Health_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xd7, 0xdb, 0x4d, 0x42, 0xa7, 0x2d, 0xbb, 0x0c, 0x12, 0x58, 0x15, 0x87, 0x2a, 0x12,
	0x55, 0xe1, 0x90, 0x43, 0x10, 0x97, 0x1e, 0x38, 0x50, 0x0a, 0x54, 0x88, 0x14, 0x39, 0xfc, 0x39,
	0xa2, 0x34, 0xb5, 0x68, 0x45, 0x9a, 0x98, 0xd8, 0x41, 0x09, 0x6f, 0xc1, 0x2b, 0xf2, 0x24, 0xc8,
	0x76, 0x4a, 0x5b, 0xd1, 0x3d, 0xfe, 0xbe, 0x99, 0xf9, 0xf4, 0x79, 0xc6, 0xd0, 0x2d, 0x45, 0x1a,
	0x88, 0xb2, 0x50, 0x05, 0x76, 0x4a, 0x91, 0xfa, 0x4f, 0xa1, 0x3f, 0x2b, 0x76, 0x22, 0xe3, 0xf5,
	0x87, 0x62, 0x9b, 0x2b, 0xec, 0x03, 0xa9, 0x29, 0x19, 0x91, 0x09, 0x61, 0xa4, 0xd6, 0xd4, 0xd0,
	0x4b, 0x4b, 0x8d, 0xff, 0x87, 0x40, 0xff, 0x65, 0x56, 0xa4, 0xdf, 0x19, 0xff, 0x51, 0x71, 0xa9,
	0xf0, 0x09, 0xb8, 0x22, 0x56, 0x49, 0xa9, 0xcc, 0x44, 0x2f, 0xbc, 0x17, 0x68, 0xf7, 0x63, 0x3f,
	0xd6, 0x36, 0xe0, 0x63, 0xb8, 0x12, 0xf3, 0x7c, 0x6d, 0xcc, 0xce, 0x36, 0x9a, 0x32, 0x3e, 0x00,
	0x57, 0x68, 0x94, 0xb4, 0x33, 0x22, 0x13, 0x87, 0xb5, 0x84, 0x43, 0xb8, 0xb3, 0x4b, 0xea, 0x85,
	0xe2, 0xa5, 0xa4, 0x57, 0xa6, 0xf2, 0x8f, 0xf1, 0x11, 0x74, 0x57, 0x3a, 0x55, 0xbc, 0xfd, 0xc5,
	0xa9, 0x63, 0x8a, 0x07, 0x41, 0x3b, 0xd6, 0x26, 0x34, 0x75, 0xad, 0xa3, 0x25, 0xad, 0x37, 0x56,
	0xf7, 0xac, 0x6e, 0xc9, 0x1f, 0x03, 0xb4, 0x6f, 0x14, 0x59, 0x83, 0x14, 0xbc, 0x92, 0xcb, 0x2a,
	0x53, 0x92, 0xc2, 0xa8, 0x33, 0x71, 0xd8, 0x1e, 0xfd, 0x00, 0xf0, 0x2d, 0x4f, 0x32, 0xb5, 0x99,
	0x6d, 0xf8, 0x61, 0x23, 0x14, 0x3c, 0xc9, 0xcb, 0x9f, 0xdb, 0x94, 0x9b, 0x95, 0x74, 0xd9, 0x1e,
	0xfd, 0xdf, 0x04, 0xee, 0x9f, 0x0c, 0x48, 0x51, 0xe4, 0x92, 0xe3, 0x0b, 0x70, 0xa5, 0x4a, 0x54,
	0x25, 0xcd, 0xc0, 0xdd, 0x70, 0x6c, 0x56, 0x73, 0xa6, 0x33, 0x88, 0xb5, 0x53, 0xfe, 0x2d, 0x36,
	0xdd, 0xac, 0x9d, 0xf2, 0xa7, 0x30, 0x38, 0x29, 0x60, 0x0f, 0xbc, 0x4f, 0xd1, 0xbb, 0x68, 0xf9,
	0x25, 0xba, 0xb9, 0xd0, 0x10, 0xcf, 0xd9, 0xe7, 0x45, 0xf4, 0xe6, 0x86, 0xe0, 0x35, 0xf4, 0xa2,
	0xe5, 0xc7, 0xaf, 0x7b, 0xe1, 0x32, 0x7c, 0x0d, 0x83, 0xf7, 0x49, 0xbe, 0xe6, 0x59, 0x6c, 0x43,
	0xe2, 0x73, 0x18, 0xe8, 0xa3, 0x54, 0x8a, 0x5b, 0x1d, 0xed, 0xa1, 0x8e, 0x8f, 0x3e, 0xbc, 0x3e,
	0x96, 0x44, 0xd6, 0xf8, 0x17, 0xe1, 0x2b, 0x70, 0x6d, 0x60, 0x9c, 0x82, 0x63, 0x42, 0xe3, 0xc3,
	0xff, 0x9f, 0x61, 0xc7, 0xe9, 0x6d, 0xef, 0x5b, 0xb9, 0xe6, 0x5b, 0x3e, 0xfb, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xc2, 0x66, 0xcd, 0x42, 0xa3, 0x02, 0x00, 0x00,
}
