---
kind: Service
apiVersion: v1
metadata:
  name: mandelbrot-service
spec:
  type: NodePort
  selector:
    app: mandelbrot
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32400
